version: "3.8"

services:


  web:
    image:  asset4342/dbpersistanceaas
    restart: always
    depends_on:
      - mongo
    ports:
      - "8003:8000"
    volumes:
      - .:/app:Z
    environment:
      SECRET_KEY: "wuiyeriuweyruiyweiuryiuewyriuewyriuyewiukjsdhbfkljhsdkjhf-test"
      DJANGO_ALLOWED_HOSTS: "*"
      DJANGO_DEBUG: 'True'
      MONGO_URL: mongodb://mongo:27017
      AAS_URL: "http://mes_app:5111/aas"
      SUBMODELS_URL: "http://mes_app:5111/aas/submodels"
      DATA_UPDATE_INTERVAL: 10
    stdin_open: true
    tty: true

  mongo:
    image: mongo
    container_name: mymongo
    volumes:
      - ./mongo_data:/data/db